// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi7XQWyDJhC75yKlnmvXvbs7Re3qaC2aQ',
    appId: '1:1050976589111:web:1ee3124788d316be9276b2',
    messagingSenderId: '1050976589111',
    projectId: 'mob-13n14-90f73',
    authDomain: 'mob-13n14-90f73.firebaseapp.com',
    databaseURL: 'https://mob-13n14-90f73-default-rtdb.firebaseio.com',
    storageBucket: 'mob-13n14-90f73.firebasestorage.app',
    measurementId: 'G-SY2NZ3346P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5MBGaGALAtf_Bpnru7frfjn9ypAEvNno',
    appId: '1:1050976589111:android:b9430addd14b4be99276b2',
    messagingSenderId: '1050976589111',
    projectId: 'mob-13n14-90f73',
    databaseURL: 'https://mob-13n14-90f73-default-rtdb.firebaseio.com',
    storageBucket: 'mob-13n14-90f73.firebasestorage.app',
  );
}
